### ISSUE TITLE
cannot add device

### ISSUE THREAD

**Issue by ericvanbeurden** [Inversion-NL/Homey-ESPhome#2]
Installed this plugin and tried to add my Gosund SP111 with ESPhome (1.17.0 May 5 2021, 15:06:55) via the mobile app
Filled in the IP, port was added automatiscly, filled in the password, but after that it takes ages. 

In case I try to repeat the process via the homey webinterface it tells me my password is wrong, while with the same password I can login on the webserver from the Gosund sP111.

Should I put the device in pairmode and how? or what should it do to add a device.

**Comment by RoadXY** [comment]
This app isn't ready for production, yet.
